import React from "react";
import styles from "./Common1.module.css";

function AdsInfo() {
  return (
    <div className={styles.container}>
      <h1 className={styles.title}>Ads Info</h1>
      <div className={styles.content}>
        <p className={styles.intro}>
          We are a restaurant management system project, built with MERN stack.
          This project is created by Rayan Ahmad, Gaurav Raj, and Chandan Kumar,
          who are students of University of Kalyani, doing B.Tech in Information
          Technology. We offer various advertising options for businesses who
          want to reach more customers and grow their brand. This page explains
          how our advertising works and what you need to know before you
          advertise with us.
        </p>
        <h2 className={styles.heading}>How our advertising works</h2>
        <p className={styles.text}>
          Our advertising works on a pay-per-click (PPC) or pay-per-impression
          (PPI) model, depending on the type of ad you choose. This means that
          you only pay when someone clicks on your ad or views your ad for a
          certain amount of time. You can set your own budget and bid for your
          ads, and we will show your ads to the most relevant and interested
          users on our project. You can also track and measure your ads
          performance and return on investment (ROI) through our dashboard,
          where you can see the number of impressions, clicks, conversions, and
          revenue generated by your ads.
        </p>
        <h2 className={styles.heading}>What types of ads do we offer</h2>
        <p className={styles.text}>
          We offer the following types of ads for your convenience and
          effectiveness:
        </p>
        <ul className={styles.list}>
          <li className={styles.item}>
            Banner ads: These are image or text ads that appear on the top,
            bottom, or side of our project pages. They are suitable for
            increasing your brand awareness and driving traffic to your website
            or landing page. They are charged on a PPI basis, and the cost
            depends on the size, position, and duration of your ad.
          </li>
          <li className={styles.item}>
            Sponsored posts: These are content-based ads that appear on our
            project blog or social media pages. They are suitable for showcasing
            your product or service features and benefits, and engaging your
            potential customers. They are charged on a PPC basis, and the cost
            depends on the quality, length, and relevance of your content.
          </li>
          <li className={styles.item}>
            Video ads: These are video ads that play before, during, or after
            our project videos or live streams. They are suitable for
            demonstrating your product or service in action, and creating an
            emotional connection with your audience. They are charged on a PPI
            basis, and the cost depends on the format, duration, and placement
            of your video.
          </li>
          <li className={styles.item}>
            Native ads: These are ads that blend in with the look and feel of
            our project pages. They are suitable for providing value and
            information to your customers, and generating leads or sales. They
            are charged on a PPC basis, and the cost depends on the type, size,
            and location of your ad.
          </li>
        </ul>
        <h2 className={styles.heading}>How to advertise with us</h2>
        <p className={styles.text}>
          To advertise with us, you need to follow these steps:
        </p>
        <ol className={styles.list}>
          <li className={styles.item}>
            Register as an advertiser on our project website and create your ad
            campaign. You can choose the type, budget, and duration of your ad,
            and customize it according to your target audience, location, and
            keywords.
          </li>
          <li className={styles.item}>
            Submit your ad for approval and wait for our feedback. We will
            review your ad and check if it meets our quality and relevance
            standards. We will also check if your ad complies with our policies,
            terms, and conditions. We will notify you of the status of your ad
            within 24 hours.
          </li>
          <li className={styles.item}>
            Pay for your ad and start your campaign. You can pay for your ad
            using any of the payment options that we accept, such as credit or
            debit card, UPI, net banking, wallet, or cash on delivery. You can
            also use our coupons or discounts to save money on your ad. Once you
            pay for your ad, we will start showing it to our users according to
            your preferences and settings.
          </li>
          <li className={styles.item}>
            Monitor and optimize your ad performance and ROI. You can access and
            analyze your ad metrics and reports through our dashboard, where you
            can see the number of impressions, clicks, conversions, and revenue
            generated by your ad. You can also make changes or adjustments to
            your ad campaign, such as pausing, resuming, or stopping your ad, or
            modifying your budget, bid, or target.
          </li>
        </ol>
        <h2 className={styles.heading}>How to contact us</h2>
        <p className={styles.text}>
          If you have any questions or feedback about our project or our
          advertising options, please feel free to contact us at
          restaurant.project@gmail.com. We are happy to help you and answer your
          queries.
        </p>
      </div>
    </div>
  );
}

export default AdsInfo;
