import React from "react";
import Styles from "./Common1.module.css";

function Advertise() {
  return (
    <div className={Styles.container}>
      <h1 className={Styles.title}>Advertise with us</h1>
      <div className={Styles.content}>
        <p className={Styles.intro}>
          Do you want to reach more customers and grow your business? Do you
          have a product or service that is relevant to the restaurant industry?
          If yes, then you should advertise with us!
        </p>
        <p className={Styles.intro}>
          We are a restaurant management system project, built with MERN stack.
          This project is created by Rayan Ahmad, Gaurav Raj, and Chandan Kumar,
          who are students of University of Kalyani, doing B.Tech in Information
          Technology. Our project helps restaurant owners and managers to manage
          their daily operations, such as inventory, orders, payments, menus,
          reservations, and more. Our project also provides a platform for
          customers to find and book their favorite restaurants, rate and review
          them, and get personalized recommendations.
        </p>
        <p className={Styles.intro}>
          Our project has a large and engaged user base, who are interested in
          dining out, food delivery, and online ordering. By advertising with
          us, you can reach these potential customers and showcase your brand,
          product, or service. You can also benefit from our analytics and
          insights, which can help you optimize your marketing strategy and
          measure your return on investment.
        </p>
        <h2 className={Styles.heading}>How to advertise with us</h2>
        <p className={Styles.text}>
          We offer various advertising options, such as banner ads, sponsored
          posts, video ads, and native ads. You can choose the option that suits
          your budget and goals. You can also customize your ads according to
          your target audience, location, and keywords. You can track and manage
          your ads performance through our dashboard, where you can see the
          number of impressions, clicks, conversions, and revenue generated by
          your ads.
        </p>
        <p className={Styles.text}>
          To advertise with us, you need to register as an advertiser on our
          website and create your ad campaign. You can also contact us at
          restaurant.project@gmail.com and we will assist you with the process.
          We accept payments through PayPal, credit card, or bank transfer. We
          charge on a cost-per-click (CPC) or cost-per-impression (CPM) basis,
          depending on the type of ad you choose. We also offer discounts for
          long-term or bulk advertising.
        </p>
        <h2 className={Styles.heading}>Why advertise with us</h2>
        <p className={Styles.text}>
          Advertising with us can help you achieve the following benefits:
        </p>
        <ul className={Styles.list}>
          <li className={Styles.item}>
            Increase your brand awareness and recognition among your target
            market.
          </li>
          <li className={Styles.item}>
            Drive more traffic and leads to your website or landing page.
          </li>
          <li className={Styles.item}>
            Boost your sales and revenue by converting more customers.
          </li>
          <li className={Styles.item}>
            Enhance your customer loyalty and retention by providing value and
            satisfaction.
          </li>
          <li className={Styles.item}>
            Gain a competitive edge over your rivals by reaching a niche and
            high-intent audience.
          </li>
        </ul>
        <p className={Styles.text}>
          Don't miss this opportunity to grow your business with us. Contact us
          today and start advertising with us!
        </p>
      </div>
    </div>
  );
}

export default Advertise;
